export default function Head() {
	return (
		<>
			<title>Create Dax Stax</title>
			<meta
				content='width=device-width, initial-scale=1'
				name='viewport'
			/>
			<meta
				name='description'
				content='Generated by create dax stax'
			/>
			{/* Add a favicon in the public folder and uncomment the bellow */}
			{/* <link rel="icon" href="/favicon.ico" /> */}
		</>
	);
}
